easy_admin:
  site_name: "<b>Backoffice</b>"
  design:
    brand_color: "green"
    menu:
      - label: "eCommerce"
        icon: "newspaper-o"
        children:
          - { entity: "Product", icon: "folder-open", label: "Produits" }
          - { entity: "Category", icon: "folder-open", label: "Catégories" }

      - label: "Accès"
        icon: "user"
        children:
          - { entity: "User", icon: "folder-open", label: "Utilisateurs" }
imports:
  - { resource: admin/ }