easy_admin:
  entities:
    Category:
      class: App\Entity\Category
      form:
        fields:
          - { property: "title", label: "Titre" }

      list:
        actions:
          - { name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary' }
          - { name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger' }

        fields:
          - { property: "title", label: "Titre" }