easy_admin:
  entities:
    User:
      class: App\Entity\User
      form:
        fields:
          - { property: "firstname", label: "Prénom" }
          - { property: "lastname", label: "Nom" }
          - { property: "email" }
          - { property: "roles", type: "collection" }

      list:
        actions:
          - { name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary' }
          - { name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger' }

        fields:
            - { property: "firstname", label: "Prénom" }
            - { property: "lastname", label: "Nom" }
            - { property: "email" }
            - { property: "roles" }